version: '3'
services:
  optimod-gateway:
    build: .
    ports:
      - "9000:9000"      # EmberPlus TCP server
      - "162:162/udp"     # SNMP traps (UDP)
    environment:
      - OPTIMOD_ADDRESS=192.168.1.100
      - SNMP_COMMUNITY=public
      - POLL_INTERVAL_MS=5000
      - EMBERPLUS_PORT=9000
      - SNMP_TRAP_PORT=162
